name = "PowerSimulationsDynamicsSurrogates"
uuid = "de933368-4bb5-470a-b916-9fff09bf2720"
authors = ["Matt Bossart"]
version = "0.1.0"

[deps]
PowerSimulationsDynamics = "398b2ede-47ed-4edc-b52e-69e4a48b4336"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"

[compat]
PowerSystems = "1"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
